/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:3380050c-8d6a-4cce-b9e2-589923fc7c0d",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_lfXvBCLez",
    "aws_user_pools_web_client_id": "521cek3v9st993s1v4d6mqqcrd",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://cbcyxcjubjadvfpdvea6cg4hk4.appsync-api.ap-south-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-south-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-bccz2hn5urg65kg4arrkergbsq",
    "aws_user_files_s3_bucket": "appambilfyapp709cd8fe6c1c4a27a9cfdc7bc4580f7391945-staging",
    "aws_user_files_s3_bucket_region": "ap-south-1"
};


export default awsmobile;
